### ISSUE TITLE
Missing error handling

### ISSUE THREAD

**Issue by danielkza** [OrKoN/native-exec#1]
`execvp` might fail and return `-1` and set `errno`, such as when the specified executable is not found. Such errors seem to be ignored, instead of propagated to JS in the form of an exception or an error callback.

**Comment by OrKoN** [comment]
@danielkza thanks, good point! If you have a chance, could you open a PR? otherwise, I will try to look into proper error handling in the near future.

**Comment by danielkza** [comment]
I don't have much experience developing Node extensions, but I can try.

**Comment by OrKoN** [comment]
I merged and published https://github.com/OrKoN/native-exec/pull/6 Thanks for fixing that!
